[package]
name = "scrt-rng"
version = "0.1.0"
authors = ["ddt"]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
#default = []
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
#default = ["debug-print"]
backtraces = ["cosmwasm-std/backtraces"]
debug-print = ["cosmwasm-std/debug-print"]

[dependencies]
cosmwasm-schema = { git = "https://github.com/enigmampc/SecretNetwork", tag = "v1.0.4-debug-print" }
#v1.0.4-debug-print
cosmwasm-std = { git = "https://github.com/enigmampc/SecretNetwork", tag = "v1.0.4-debug-print" }
cosmwasm-storage = { git = "https://github.com/enigmampc/SecretNetwork", tag = "v1.0.4-debug-print" }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
snafu = { version = "0.6.3" }
subtle = { version = "2.2.3", default-features = false }
base64 = "0.12.3"
hex = "0.4.2"

secret-toolkit = { git = "https://github.com/enigmampc/secret-toolkit", tag = "v0.1.1-debug-print" }
#, tag = "v0.1.1-debug-print" }

#serde-json-wasm = "0.2.1"
#x25519-dalek = "1.1"
rand = "0.7.3"
#"0.8.4" maybe too new does not work
getrandom = { version = "0.2", features = ["js"] }
rand_chacha = "0.2.2"
#"0.3.1" maybe too new does not work
sha2 = { version = "0.9.1", default-features = false }

